### PR TITLE
Basic 1.20 Port

### PR DESCRIPTION
**Pull request by sleepingdragoninn**
It runs! that's the long and short of it. There's nothing fancy here, block state instantiation just changed. Edit whatever you like, it's ur arr

### CODE REVIEW

**Comment by sleepingdragoninn** [comment]
Hey hello! Any chance of this getting a look? I'm happy to just redistribute the jar with permission, but otherwise I can't modpack it ^^

**Comment by thcrt** [comment]
I'd love to include this in my own pack. Do you have Discord? Maybe you could contact @CammiePone on there if they're not responding here. I'd do it myself but I don't have a Discord account.

It would be a shame if the mod became abandoned :(

**Comment by CammiePone** [comment]
oh yeah. i completely forgot about this tbh. yea i can push it

**Comment by thcrt** [comment]
Thank you! <3

**Pull request merged**
